steps:
  - checkout: RushstackMainRepo
    path: rushstack

  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'
    workingDirectory: '$(Agent.BuildDirectory)/rushstack'

  - script: 'git config --local user.name Rushbot'
    displayName: 'git config name'
    workingDirectory: '$(Agent.BuildDirectory)/rushstack'

  - script: 'node common/scripts/install-run-rush.js install --to repo-toolbox'
    displayName: 'Rush Install (rushstack)'
    workingDirectory: '$(Agent.BuildDirectory)/rushstack'

  - script: 'node common/scripts/install-run-rush.js build --verbose --production --to repo-toolbox'
    displayName: 'Rush Rebuild (rushstack)'
    workingDirectory: '$(Agent.BuildDirectory)/rushstack'

  - script: 'node $(Agent.BuildDirectory)/rushstack/repo-scripts/repo-toolbox/lib/start.js record-versions --out-file $(Build.ArtifactStagingDirectory)/published-versions/published-versions.json'
    displayName: 'Record Published Versions'
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'

  - script: 'node repo-scripts/repo-toolbox/lib/start.js collect-json-schemas --output-path $(Build.ArtifactStagingDirectory)/json-schemas'
    displayName: 'Collect JSON Schemas'
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'

